### ISSUE TITLE
Unable to Trigger OTA

### ISSUE THREAD

**Issue by janstadt** [kendallgoto/switchbota#25]
I have a new switchbot mini plug that i have paired with a phone (tried both android and iphone). I can connect to the switch and toggle it fine. I have the server up and running and the DNS entry working. I can see requests going to the local webserver but i cannot figure out how to trigger the apps OTA firmware check. The firmware version states its V1.3 but i cant seem to kick in the OTA for patching. Any ideas as to how to trigger it? I read somewhere to pull down on the devices page and on the firmware page to make it make the request but that doesnt seem to do anything other than make a request to: `::ffff:192.168.1.75 - /version/wocaotech/release.json`

Any help would be greatly appreciated.

**Comment by kendallgoto** [comment]
It's somewhat tedious, but you can manually issue a command over BLE to the device to start the update process. 

See here:
https://github.com/kendallgoto/switchbota/issues/3#issuecomment-1121864522

**Comment by janstadt** [comment]
Thanks @kendallgoto. Just finishing up the manual BLE forced update!

**Comment by janstadt** [comment]
@kendallgoto do you plan on investigating how to get this to trigger more automatically or how/why it does it automatically for some but not other BLE devices?

**Comment by linagee** [comment]
I think newer versions of manufacturer firmware will require a manual BLE trigger and old ones worked without a manual trigger. This seemed to happen for me around v1.3 or so. Using #3 was not tedious for me. If users normally have BLE on the laptop/etc they run switchbOTA from, the manual trigger could probably be sent. (Even fancier might be to read the current manufacturer firmware version, if that's possible, which it likely is if the app can do it.)

**Comment by kendallgoto** [comment]
yes - the required firmware version is requested over TLS (mqtt over tls iirc?) and thus cannot easily be spoofed to prompt for an update in the app. Because of that, if there is no update already pending on the device, you have to force it manually with the BLE command.

I'm not super interested in sending the bluetooth commands directly as part of SwitchbOTA -- if someone wants to make a PR for it, maybe. I did so in this previous project: https://github.com/kendallgoto/switchbot-plug-influxdb - but I found that the cross-platform support for BLE was awful. It didn't work effectively on my OSX laptop, my Windows PC, and only successfully ran off a Linux VM, with a good amount of trickery. IMO, suggesting to use nRF Connect / etc is just easier to maintain.
